name: Exemplos e contra-exemplos de páginas acessíveis
markdown: kramdown
url: http://talitapagani.com/paginas-acessiveis
include: ['_pages']
collections:
  examples:
    output: true
    permalink: /:collection/:title/
description: TBD